arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
  - tegra          # [false]
# https://docs.nvidia.com/cuda/nvjpeg2000/userguide.html#platforms-supported
c_stdlib_version:  # [aarch64]
  - 2.17  # [linux64]
  - 2.28  # [aarch64]
