build_platform:
  linux_aarch64: linux_aarch64
provider:
  linux_aarch64: default
os_version:
  linux_64: cos7
  linux_aarch64: alma8
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
